### ISSUE TITLE
citeパッケージと併用した場合に上手く動かない

### ISSUE THREAD

**Issue by nakashin303** [ehki/jIEEEtran#58]
citeパッケージを使用して複数の引用を一つにまとめようとすると、TeX中には`\cite{A,B,C}`と記載することになると思います。このうち一つの引用で英語/日本語の併記をしようと`\cite{Ae/ej/Aj,B,C}`などと記載すると、`Ae`と`Aj,B,C`であると認識されてしまい上手く処理できないです。

**Comment by ehki** [comment]
ありがとうございます。
`\cite{Ae,Aj,B,C}`と切り分けてBibtexに処理させて、`\cite{Ae/ej/Aj,B,C}`に戻す方式でもちゃんと処理できそうですね。
citeパッケージがない場合でも、上の処理で問題なくコンパイルできていますので、そう変更します。
