### ISSUE TITLE
IEEJtran.bstでの英語文献の章と雑誌名の取り扱いについて

### ISSUE THREAD

**Issue by hs0876** [ehki/jIEEEtran#60]
IEEJtran.bstではIncollectionの英語文献は「ch.4」のように章を記載していますが、Chap.4が正しいらしいです。
また、英語文献の雑誌名はイタリックにするのが正しいらしいです。

**Comment by ehki** [comment]
ありがとうございます！
新しい文献で検索をかけてみると

イタリックの取り扱いは
https://www.jstage.jst.go.jp/article/ieejias/140/3/140_184/_pdf/-char/ja
https://www.jstage.jst.go.jp/article/ieejpes/140/3/140_219/_pdf/-char/ja

Chap. の取り扱いは
https://www.jstage.jst.go.jp/article/ieejeiss/139/11/139_1348/_pdf/-char/ja

あたりに従えばよいのでしょうかね。
