### ISSUE TITLE
読点と全角カンマ

### ISSUE THREAD

**Issue by hs0876** [ehki/jIEEEtran#62]
サンプルtexファイルで読点を使っていると思いますが、電気学会形式にするのであれば全角カンマを使うべきだと思います。

**Comment by ehki** [comment]
ありがとうございます！そのとおりで全角カンマのほうが良いです！

**Comment by ehki** [comment]
あれ、自動で閉じられませんね。。。developからmasterにマージしましたので閉じさせていただきます。また修正/修正依頼お願いしますね。
