### ISSUE TITLE
参考文献の短縮表記

### ISSUE THREAD

**Issue by nakashin303** [ehki/jIEEEtran#64]
次のような参考文献の短縮表記ができないでしょうか。
例）
R. Schurch, S. M. Rowland, R. S. Bradley, and P. J. Withers, “Imaging and analysis techniques for electrical trees using X-ray computed tomography,” _IEEE Transactions on Dielectrics and  Electrical Insulation_, vol. 21, no. 1, pp. 53–63, 2014.
を
R. Schurch, _et al_., _IEEE Trans. Dielectr. Electr. Insul_, **21**, 1, 53–63, 2014.

**Comment by ehki** [comment]
できそうです。電気学会ではその形式は目にするので対応できるようにします。IEEJtranA.bstというbstファイルを新たに作成します。IEEEの学会でも短縮形式の引用は見かけますか？

**Comment by nakashin303** [comment]
P. Mancinelli, A. Cavallini, S. J. Dodd, N. M. Chalashlanov and L. A. Dissado, “Analysis of electrical tree inception in silicone gels,” IEEE Trans. Dielectr. Electr. Insul., vol. 24, no. 6, pp. 3974–3984, 2017.
のような論文誌名の短縮表記はよく見かけます。

**Comment by ehki** [comment]
その形式の引用への変更は、例えばMendeleyでは「Preference」から「BibTeX」タブへと進み、「Use Journal Abbreviation」にチェックを入れれば可能です。つまり、bstファイルとbibtexコマンドのタスクではなく、.bibファイル上の情報を変更する必要があります。bstファイルでも不可能ではないですが、膨大な省略を定義しなければならず、現実的ではなさそうです。

Mendeleyの場合(私がMendeleyを使用しているからMendeley以外はわからないのですが)「View」から「Citation Style」へと進み、「Journal Abbreviations」の「Abbreviations」タブで省略を自分で定義することも可能です。例えば次のように省略形式を定義し、`Cite Using`を`Acronym`と設定すれば、Mendeleyから「電学論A」というjournal名でbibファイルを出力することができます。
- Journal Name: 電気学会論文誌 A 基礎・材料・共通部門誌
- Default: 電気学会論文誌 A
- Acronym: 電学論A


IEEEのjournalだけに関しては、journal名に`IEEE_J_PWRD`等のマクロ指定のマジックコマンドを入れて、`IEEEabrv.bib`や`IEEEfull.bib`を引用することで省略形式やフル形式への変更が可能です。ただIEEE以外にはこの手法が使えないので、文献管理ツール側で出力するbibファイルを操作することを推奨します。

**Comment by ehki** [comment]
v0.15で`article`及び`inprceedings`エントリで対応しました。このIssueは閉じますので、他のエントリでの引用については別Issueでお願いします。
