### ISSUE TITLE
Authorがスペースの無い文字列のときに先頭にスペースが入る

### ISSUE THREAD

**Issue by monhime** [ehki/jIEEEtran#66]
Authorが機関名などで途中にスペースが無いとき、その出力の先頭にスペースが入ってしまいます。

**Comment by yuichi-hirano711** [comment]
2人以上の場合、First Authorが姓名の間にスペースが無ければバグが起こり、2nd Author以降の書き方は関係ないみたいです。

**Comment by ehki** [comment]
ありがとうございます。
機関のようにスペースがない著者はラストネーム扱いになり、日本語文献ではファーストネームとラストネームの間にチルダを入れる処理になっていたことが問題でした。日本語文献の場合に
- 通常通りの処理で`"{ff}~{vv~}{ll}{, jj}"`を通した文字列
- `"~{ll}"`とラストネームの前にチルダを入れた文字列

この２つを比較して同一であった場合に機関名と判断し、`"{ll}"`を通した文字列を出力することで回避します。
